services:
  prod.market-api-order:
    image: market-api-order:latest
    restart: always
    environment:
      APP_NAME: market-api-order
      SPRING_PROFILE: prod
    volumes:
      - market_upload:/upload
    networks:
      - prod-default

  local.market-api-order:
    image: market-api-order:latest
    restart: always
    environment:
      APP_NAME: market-api-order
      SPRING_PROFILE: local
    volumes:
      - market_upload:/upload
    networks:
      - local-default

volumes:
  market_upload:

networks:
  prod-default:
    external: true
  local-default:
    external: true