stages:
  - build

cache:
  paths:
    - ${CI_PROJECT_DIR}/envs

variables:
  CACHE_ENV_PATH: ${CI_PROJECT_DIR}/envs
  MAVEN_OPTS: "-Dmaven.repo.local=${CACHE_ENV_PATH}/${CI_COMMIT_REF_NAME}/.m2/repository"
  MAVEN_SETTINGS: ./.mvn/wrapper/settings.xml

build-maven:
  stage: build
  image: amazoncorretto:17-alpine-jdk
  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
  script:
    - ls -al "${JAVA_HOME}/bin/java"
    - chmod u+x ./mvnw
    - ./mvnw ${MAVEN_OPTS} clean deploy -s ${MAVEN_SETTINGS}
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days
  only:
    #- dev
    - prod
