/*
*/

DROP SEQUENCE SCIENTIST_SEQ;
CREATE SEQUENCE SCIENTIST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


DROP TABLE SCIENTIST;
CREATE TABLE SCIENTIST 
(
  ID INT PRIMARY KEY,
  NAME VARCHAR2(255),
  CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATE_ID INT DEFAULT 1,
  MODIFY_ID INT DEFAULT 1
);

INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Galileo Galilei');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Johannes Kepler');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Isaac Newton');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Dmitri Mendeleev');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Albert Einstein');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Stephen Hawking');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Nikola Tesla');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Niels Bohr');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Michael Faraday');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'James Clerk Maxwell');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Alan Turing');
INSERT INTO SCIENTIST (ID, NAME) VALUES(SCIENTIST_SEQ.NEXTVAL, 'Richard Feynman');
