services:
  prod.common-auth:
    image: common-auth:latest
    restart: always
    environment:
      APP_NAME: common-auth
      SPRING_PROFILE: prod
    networks:
      - prod-default

  local.common-auth:
    image: common-auth:latest
    restart: always
    environment:
      APP_NAME: common-auth
      SPRING_PROFILE: local
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true