services:
  prod.common-gateway:
    image: common-gateway:latest
    restart: always
    environment:
      APP_NAME: common-gateway
      SPRING_PROFILE: prod
    networks:
      - prod-default

  local.common-gateway:
    image: common-gateway:latest
    restart: always
    environment:
      APP_NAME: common-gateway
      SPRING_PROFILE: local
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true